webbanxe/Models/Slide.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace webbanxe.Models
{
    public class Slide

    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(500)]
        public string Title { get; set; }
        
        [Required]
        [StringLength(500)]
        public string SloganTitle { get; set; }
        
        [Required]
        [StringLength(500)]
        [ValidateNever]
        public string NameImg { get; set; }

        [NotMapped]
        [ValidateNever]
        public IFormFile ImageFile { get; set; }
    }
}

webbanxe/Areas/Admin/Controllers/SlidesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webbanxe.Data;
using webbanxe.Models;
using webbanxe.Models.Authentications;
using webbanxe.Utilities;

namespace webbanxe.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlidesController : Controller
    {
        private readonly DataContext _context;

        public SlidesController(DataContext context)
        {
            _context = context;
        }

        // GET: Admin/Slides
        [Authentication]
        public async Task<IActionResult> Index()
        {
              return _context.Slides != null ? 
                          View(await _context.Slides.ToListAsync()) :
                          Problem("Entity set 'DataContext.Slides'  is null.");
        }

        // GET: Admin/Slides/Details/5
        [Authentication]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Slides == null)
            {
                return NotFound();
            }

            var slide = await _context.Slides
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slide == null)
            {
                return NotFound();
            }

            return View(slide);
        }

        [HttpGet]
        [Authentication]
        public async Task<IActionResult> CreateOrUpdate(int? id)
        {
            var slide = await _context.Slides.FirstOrDefaultAsync(m => m.Id == id);
            if(slide == null)
            {
                slide = new Slide();
            }
            return View(slide);
        }
            // GET: Admin/Slides/Create
            public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> CreateOrUpdate(Slide slide)
        {
            if (ModelState.IsValid)
            {
                if (slide.Id == 0)
                {
                    if (slide.ImageFile != null)
                    {
                        slide.NameImg =   Functions.saveSingleImage(slide.ImageFile);
                        _context.Slides.Add(slide);
                    }
                }
                else
                {
                    var oldSlide = await _context.Slides
                          .FirstOrDefaultAsync(m => m.Id == slide.Id);

                    if (slide.ImageFile != null)
                    {
                        slide.NameImg = Functions.saveSingleImage(slide.ImageFile);
                        Functions.deleteSingleImage(oldSlide.NameImg);
                    }
                    else
                    {
                        slide.NameImg = oldSlide.NameImg;
                    }    
                    _context.Slides.Update(slide);
                }
            }
            _context.SaveChanges();
            return RedirectToAction("Index");

        }


        // GET: Admin/Slides/Delete/5
        [Authentication]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Slides == null)
            {
                return NotFound();
            }

            var slide = await _context.Slides
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slide == null)
            {
                return NotFound();
            }

            return View(slide);
        }

        // POST: Admin/Slides/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Slides == null)
            {
                return Problem("Entity set 'DataContext.Slides'  is null.");
            }
            var slide = await _context.Slides.FindAsync(id);

            Functions.deleteSingleImage(slide.NameImg);
            if (slide != null)
            {
                _context.Slides.Remove(slide);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SlideExists(int id)
        {
          return (_context.Slides?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

webbanxe/Areas/Admin/Views/Slides/CreateOrUpdate.cshtml
@model webbanxe.Models.Slide
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Slide</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Home</a></li>
                <li class="breadcrumb-item"><a>Post</a></li>
                <li class="breadcrumb-item active">Add </li>
            </ol>
        </nav>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
    <section class="section dashboard">
        <div class="row">
            <div class="col-md-12">
        <form asp-action="CreateOrUpdate" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" type="hidden" />
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SloganTitle" class="control-label"></label>
                <input asp-for="SloganTitle" class="form-control" />
                <span asp-validation-for="SloganTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameImg" class="control-label"></label>
                <input asp-for="ImageFile" type="file" accept="image/*" class="form-control" />
                <span asp-validation-for="NameImg" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    </div>
    </section>
    </main>


<div>
    <a asp-action="Index">Back to List</a>
</div>

webbanxe/Areas/Admin/Views/Slides/Delete.cshtml
@model webbanxe.Models.Slide
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}
<h1>Delete</h1>
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Slide</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Home</a></li>
                <li class="breadcrumb-item"><a>Post</a></li>
                <li class="breadcrumb-item active">Add </li>
            </ol>
        </nav>
    </div>
    
    <section class="section dashboard">
        <div class="row">
            <div class="col-md-12">
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Slide</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SloganTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SloganTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameImg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameImg)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</div>
</div>
</section>
</main>

webbanxe/Areas/Admin/Views/Slides/Details.cshtml
@model webbanxe.Models.Slide
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}
<h1>Details</h1>
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Slide</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Home</a></li>
                <li class="breadcrumb-item"><a>Post</a></li>
                <li class="breadcrumb-item active">Add </li>
            </ol>
        </nav>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
    <section class="section dashboard">
        <div class="row">
            <div class="col-md-12">
<div>
    <h4>Slide</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SloganTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SloganTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameImg)
        </dt>
        <dd class = "col-sm-10">
           <img src="~/img/@Model.NameImg"  width="400px" height="auto"/>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>
</div>
</section>
</main>

webbanxe/Areas/Admin/Views/Slides/Index.cshtml
@model IEnumerable<webbanxe.Models.Slide>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Bike</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Home</a></li>
                <li class="breadcrumb-item"><a>Slide</a></li>
                <li class="breadcrumb-item active">List</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <p>
        <a asp-action="CreateOrUpdate" asp-controller="Slides">Thêm Slide</a>
    </p>
    <section class="section dashboard">
        <div class="row">
            <div class="col-lg-12">

                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.SloganTitle)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NameImg)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SloganTitle)
                                </td>
                                <td>
                                    <img src="~/img/@item.NameImg" width="75px" height="75px" />
                                </td>
                                <td>
                                    <a asp-action="CreateOrUpdate" asp-route-id="@item.Id">Edit</a> |
                                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</main>