webbanxe/Models/Accessary.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace webbanxe.Models
{
    public class Accessary
    {
        [Key]
        public int IdAccessary { get; set; }


        [Required]
        [MaxLength(500)]  
        public string NameAccessary { get; set; }
        [Required]
        public string DescriptionAccessary { get; set;}

        [Required]
        [StringLength(700)]
        [ValidateNever]
        public string ImageAccessary { get; set; }

        public double Price { get; set; }
        public double PricePromotion { get; set; }

        public int Quantity { get; set; }

        [NotMapped]
        [DisplayName("Upload File")]
        [ValidateNever]
        public List<IFormFile> ImageFile { get; set; }
    }
}

webbanxe/Areas/Admin/Controllers/AccessariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webbanxe.Data;
using webbanxe.Models;
using webbanxe.Models.Authentications;
using webbanxe.Models.ModelView;
using webbanxe.Utilities;

namespace webbanxe.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AccessariesController : Controller
    {
        private readonly DataContext _context;

        public AccessariesController(DataContext context)
        {
            _context = context;
        }

        // GET: Admin/Accessaries
        [Authentication]
        public async Task<IActionResult> Index()
        {
              return _context.Accessaries != null ? 
                          View(await _context.Accessaries.ToListAsync()) :
                          Problem("Entity set 'DataContext.Accessaries'  is null.");
        }

        // GET: Admin/Accessaries/Details/5
        [Authentication]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Accessaries == null)
            {
                return NotFound();
            }

            var accessary = await _context.Accessaries
                .FirstOrDefaultAsync(m => m.IdAccessary == id);
            if (accessary == null)
            {
                return NotFound();
            }

            return View(accessary);
        }

        // GET: Admin/Accessaries/CreateOrUpdate
        [Authentication]
        public async Task<IActionResult> CreateOrUpdate(int? id)
        {
            return await _context.Accessaries.FirstOrDefaultAsync(m => m.IdAccessary == id)!= null
                ?
                View(await _context.Accessaries.FirstOrDefaultAsync(m => m.IdAccessary == id)):
                View(new Accessary());
        }


        // POST: Admin/Accessaries/CreateOrUpdate
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> CreateOrUpdate( Accessary accessary)
        {
            if (ModelState.IsValid)
            {
                if (accessary.IdAccessary == 0)
                {
                    if (accessary.ImageFile != null)
                    {
                      accessary.ImageAccessary =  Functions.saveMutiImage(accessary.ImageFile);
                    }
                    _context.Accessaries.Add(accessary);
                }
                else
                {
                    var oldAccessaries = await _context.Accessaries.FindAsync(accessary.IdAccessary);
                    if (accessary.ImageFile != null)
                    {
                        accessary.ImageAccessary = Functions.saveMutiImage(accessary.ImageFile);
                        Functions.deleteMutiImage(oldAccessaries.ImageAccessary);
                    }
                    else
                    {
                        accessary.ImageAccessary = oldAccessaries.ImageAccessary;
                    }

                    _context.Accessaries.Update(accessary);
                }
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(accessary);
            }
        }

        // GET: Admin/Accessaries/Edit/5
        [Authentication]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Accessaries == null)
            {
                return NotFound();
            }

            var accessary = await _context.Accessaries.FindAsync(id);
            if (accessary == null)
            {
                return NotFound();
            }
            return View(accessary);
        }

        // POST: Admin/Accessaries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]
        public async Task<IActionResult> Edit(int id, [Bind("IdAccessary,NameAccessary,DescriptionAccessary,ImageAccessary,Price,PricePromotion")] Accessary accessary)
        {
            if (id != accessary.IdAccessary)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(accessary);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccessaryExists(accessary.IdAccessary))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(accessary);
        }

        // GET: Admin/Accessaries/Delete/5
        [Authentication]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Accessaries == null)
            {
                return NotFound();
            }

            var accessary = await _context.Accessaries
                .FirstOrDefaultAsync(m => m.IdAccessary == id);
            if (accessary == null)
            {
                return NotFound();
            }

            return View(accessary);
        }

        // POST: Admin/Accessaries/Delete/5
        [Authentication]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Accessaries == null)
            {
                return Problem("Entity set 'DataContext.Accessaries'  is null.");
            }
            var accessary = await _context.Accessaries.FindAsync(id);
            if (accessary != null)
            {
                _context.Accessaries.Remove(accessary);
            }
            Functions.deleteMutiImage(accessary.ImageAccessary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AccessaryExists(int id)
        {
          return (_context.Accessaries?.Any(e => e.IdAccessary == id)).GetValueOrDefault();
        }
    }
}

webbanxe/Areas/Admin/Views/Accessaries/CreateOrUpdate.cshtml
@model webbanxe.Models.Accessary
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<script src="~/ckeditor/ckeditor.js"></script>

<main id="main" class="main">

    <div class="pagetitle">
        <h1> Accessaries</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Home</a></li>
                <li class="breadcrumb-item"><a>Accessaries</a></li>
                <li class="breadcrumb-item active">Add</li>
            </ol>
        </nav>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
<h4>Accessary</h4>
<hr />
<div class="row">
            <div class="col-md-12">
        <form asp-action="CreateOrUpdate" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="IdAccessary" />
                <label asp-for="NameAccessary" class="control-label"></label>
                <input asp-for="NameAccessary" class="form-control" />
                <span asp-validation-for="NameAccessary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionAccessary" class="control-label"></label>
                <textarea asp-for="DescriptionAccessary" class="form-control"></textarea>
                    <span asp-validation-for="DescriptionAccessary" class="text-danger"></span>
                    <script>
                        CKEDITOR.replace("DescriptionAccessary");
                    </script>
            </div>
            <div class="form-group">
                <label asp-for="ImageAccessary" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageAccessary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PricePromotion" class="control-label"></label>
                <input asp-for="PricePromotion" class="form-control" />
                <span asp-validation-for="PricePromotion" class="text-danger"></span>
            </div>

                <div class="form-group">
                    <label asp-for="Quantity" class="control-label"></label>
                    <input asp-for="Quantity" class="form-control" />
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

webbanxe/Areas/Admin/Views/Accessaries/Delete.cshtml
@model webbanxe.Models.Accessary

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Accessaries</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Home</a></li>
                <li class="breadcrumb-item"><a>Accessaries</a></li>
                <li class="breadcrumb-item active">Delete</li>
            </ol>
        </nav>
    </div>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Accessary</h4>
        <hr />
        <section class="section dashboard">
            <div class="row">
                <div class="col-md-12">
                    <dl class="row">
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.NameAccessary)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.NameAccessary)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.DescriptionAccessary)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.DescriptionAccessary)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.ImageAccessary)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.ImageAccessary)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Price)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Price)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.PricePromotion)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.PricePromotion)
                            </dd>
                        </dl>

                        <form asp-action="Delete">
                            <input type="hidden" asp-for="IdAccessary" />
                            <input type="submit" value="Delete" class="btn btn-danger" /> |
                            <a asp-action="Index">Back to List</a>
                        </form>
                </div>
            </div>
        </section>
</main>

webbanxe/Areas/Admin/Views/Accessaries/Details.cshtml
@model webbanxe.Models.Accessary

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Accessary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameAccessary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameAccessary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionAccessary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionAccessary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageAccessary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageAccessary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PricePromotion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PricePromotion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdAccessary">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

webbanxe/Areas/Admin/Views/Accessaries/Edit.cshtml
@model webbanxe.Models.Accessary
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}

<h1>Edit</h1>

<h4>Accessary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdAccessary" />
            <div class="form-group">
                <label asp-for="NameAccessary" class="control-label"></label>
                <input asp-for="NameAccessary" class="form-control" />
                <span asp-validation-for="NameAccessary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionAccessary" class="control-label"></label>
                <input asp-for="DescriptionAccessary" class="form-control" />
                <span asp-validation-for="DescriptionAccessary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageAccessary" class="control-label"></label>
                <input asp-for="ImageAccessary" class="form-control" />
                <span asp-validation-for="ImageAccessary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PricePromotion" class="control-label"></label>
                <input asp-for="PricePromotion" class="form-control" />
                <span asp-validation-for="PricePromotion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

webbanxe/Areas/Admin/Views/Accessaries/Index.cshtml
@model IEnumerable<webbanxe.Models.Accessary>

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}


<main id="main" class="main">

    <div class="pagetitle">
        <h1>Accessaries</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a>Home</a></li>
                <li class="breadcrumb-item"><a>Accessaries</a></li>
                <li class="breadcrumb-item active">List</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <p>
        <a asp-action="CreateOrUpdate" asp-controller="Accessaries">Thêm phụ tùng - phụ kiên</a>
    </p>
    <section class="section dashboard">
        <div class="row">
            <div class="col-lg-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.NameAccessary)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DescriptionAccessary)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ImageAccessary)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Price)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PricePromotion)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NameAccessary)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DescriptionAccessary)
                                </td>
                                
                                <td>
                                        @foreach (var i in item.ImageAccessary.Split(";"))
                                        {
                                        <img src="~/img/@i" width="100px" height="100px">
                                        }
                                </td>
                              
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PricePromotion)
                                </td>
                                <td>
                                    <a asp-action="CreateOrUpdate" asp-route-id="@item.IdAccessary">Edit</a> |
                                    <a asp-action="Details" asp-route-id="@item.IdAccessary">Details</a> |
                                    <a asp-action="Delete" asp-route-id="@item.IdAccessary">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</main>